# Setup
title:               Lucia Jeon's Blog
tagline:             'blog.luciajeon.com'
description:         'Reach out to me via <a href="https://www.linkedin.com/in/luciajeon/" target="_blank">Linkedin</a> .'
#url:                 '/'
#baseurl:             '/'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Lucia Jeon
#  url:               '/'
  email:             luciaajeon@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
